"""
screensaver_window.py
-----------------------
Renders the user-selected HTML file full-screen, borderless, on top of
everything, across every connected monitor.

Design notes:
- One QWebEngineView per QScreen. Each gets its own independent Chromium
  page instance loading the same local file -- simplest and most reliable
  approach (avoids the complications of texture-mirroring one GPU surface
  across displays with different DPI/scaling/refresh rates).
- Windows are frameless, always-on-top, and geometry is pinned exactly to
  each QScreen's geometry (covers the taskbar too).
- ANY input (mouse move beyond a small dead-zone, click, key press, or
  touch/gesture event -- Qt normalizes touch/trackpad gestures into
  synthesized mouse/wheel/gesture events, so a single filter covers all
  of them) closes every window immediately.
- A small mouse-move dead-zone (a few pixels) prevents ultra-sensitive
  trackpads/mice from re-triggering on electrical noise the instant the
  screensaver appears -- standard screensaver behavior on every OS.
"""

from __future__ import annotations

from PySide6.QtCore import Qt, QUrl, QPoint, Signal, QObject, QEvent, QFileSystemWatcher
from PySide6.QtGui import QGuiApplication, QCursor
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import QWidget, QVBoxLayout

from .content_source import is_url, resolve_url

DEAD_ZONE_PX = 10


class _GlobalInputFilter(QObject):
    """Installed as an application-wide event filter while the screensaver
    is active. Emits `activity` the moment it sees real user input on any
    of the screensaver windows."""

    activity = Signal()

    def __init__(self, origin_pos: QPoint, parent=None):
        super().__init__(parent)
        self._origin_pos = origin_pos
        self._armed = False  # ignore the synthetic move Qt sends on show()

    def eventFilter(self, obj, event) -> bool:
        et = event.type()

        if et in (QEvent.MouseButtonPress, QEvent.KeyPress,
                   QEvent.TouchBegin, QEvent.Gesture, QEvent.Wheel):
            self.activity.emit()
            return True

        if et == QEvent.MouseMove:
            if not self._armed:
                # First move event after showing full-screen windows can be
                # a synthetic one generated by the window manager; arm the
                # real check starting now instead of trusting it.
                self._armed = True
                self._origin_pos = QCursor.pos()
                return False
            current = QCursor.pos()
            delta = current - self._origin_pos
            if abs(delta.x()) > DEAD_ZONE_PX or abs(delta.y()) > DEAD_ZONE_PX:
                self.activity.emit()
            return False

        return False


class _MonitorWindow(QWidget):
    """A single borderless, always-on-top, full-screen window pinned to
    one physical monitor, hosting a QWebEngineView."""

    def __init__(self, screen, content_url: QUrl, dev_mode: bool = False):
        super().__init__()
        self.setWindowFlags(
            Qt.FramelessWindowHint
            | Qt.WindowStaysOnTopHint
            | Qt.Tool  # keeps it out of the taskbar / alt-tab list
        )
        self.setAttribute(Qt.WA_DeleteOnClose)
        self.setCursor(Qt.BlankCursor)
        self.setStyleSheet("background-color: black;")

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self.web_view = QWebEngineView(self)
        self.web_view.setCursor(Qt.BlankCursor)

        if dev_mode:
            # A dedicated, cache-disabled profile so edits to the HTML
            # file show up on the next reload instead of being served
            # from Chromium's disk/memory cache -- essential while
            # actively developing the screensaver content.
            from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage
            self._profile = QWebEngineProfile(self.web_view)
            self._profile.setHttpCacheType(QWebEngineProfile.HttpCacheType.NoCache)
            self._profile.setPersistentCookiesPolicy(
                QWebEngineProfile.PersistentCookiesPolicy.NoPersistentCookies
            )
            page = QWebEnginePage(self._profile, self.web_view)
            self.web_view.setPage(page)

        settings = self.web_view.settings()
        # Enable the modern-web feature set requested: WebGL, local
        # playback, JS, etc. Most of these are on by default in current
        # QtWebEngine, but set explicitly for reliability across versions.
        from PySide6.QtWebEngineCore import QWebEngineSettings
        settings.setAttribute(QWebEngineSettings.WebAttribute.JavascriptEnabled, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.WebGLEnabled, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.Accelerated2dCanvasEnabled, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.PlaybackRequiresUserGesture, False)
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessFileUrls, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessRemoteUrls, False)

        layout.addWidget(self.web_view)
        self.web_view.load(content_url)

        geo = screen.geometry()
        self.setGeometry(geo)
        self._screen = screen

    def show_fullscreen_on_screen(self):
        self.setGeometry(self._screen.geometry())
        self.setCursor(Qt.BlankCursor)
        self.web_view.setCursor(Qt.BlankCursor)
        self.showFullScreen()
        self.raise_()
        self.activateWindow()

    def reload_content(self):
        self.web_view.reload()

    def closeEvent(self, event):
        # Explicitly restore the cursor rather than relying on window
        # teardown to implicitly clear it.
        self.unsetCursor()
        self.web_view.unsetCursor()
        super().closeEvent(event)


class ScreensaverController(QObject):
    """Owns the set of per-monitor windows and the global input filter.
    Emits `closed` once the screensaver has been dismissed."""

    closed = Signal()

    def __init__(self, content_source: str, app, dev_mode: bool = False):
        super().__init__()
        self._app = app
        self._windows: list[_MonitorWindow] = []
        self._filter: _GlobalInputFilter | None = None
        self._content_source = content_source
        self._dev_mode = dev_mode
        self._watcher: QFileSystemWatcher | None = None

    def start(self):
        url = resolve_url(self._content_source)
        for screen in QGuiApplication.screens():
            win = _MonitorWindow(screen, url, dev_mode=self._dev_mode)
            self._windows.append(win)

        self._filter = _GlobalInputFilter(QCursor.pos(), parent=self._app)
        self._filter.activity.connect(self._on_activity)
        self._app.installEventFilter(self._filter)

        for win in self._windows:
            win.show_fullscreen_on_screen()

        # Watch for monitors being connected/disconnected while active
        # (hot-plug) and rebuild the window set to match.
        QGuiApplication.instance().screenAdded.connect(self._on_screens_changed)
        QGuiApplication.instance().screenRemoved.connect(self._on_screens_changed)

        # Dev mode + local file: watch for edits and hot-reload every
        # monitor's view the moment the file is saved.
        if self._dev_mode and not is_url(self._content_source):
            self._watcher = QFileSystemWatcher([self._content_source])
            self._watcher.fileChanged.connect(self._on_content_file_changed)

    def _on_content_file_changed(self, path: str):
        for win in self._windows:
            win.reload_content()
        # Many editors save by replacing the file (new inode), which
        # drops it from the watch list -- re-add it so subsequent saves
        # keep triggering a reload.
        if self._watcher and path not in self._watcher.files():
            self._watcher.addPath(path)

    def _on_screens_changed(self, *_args):
        # Simplest robust approach to hot-plug: tear down and rebuild the
        # per-monitor window set against the current screen list.
        for win in self._windows:
            win.close()
        self._windows.clear()
        url = resolve_url(self._content_source)
        for screen in QGuiApplication.screens():
            win = _MonitorWindow(screen, url, dev_mode=self._dev_mode)
            self._windows.append(win)
            win.show_fullscreen_on_screen()

    def _on_activity(self):
        self.stop()

    def stop(self):
        if self._filter:
            self._app.removeEventFilter(self._filter)
            self._filter.deleteLater()
            self._filter = None
        if self._watcher:
            self._watcher.deleteLater()
            self._watcher = None
        try:
            QGuiApplication.instance().screenAdded.disconnect(self._on_screens_changed)
            QGuiApplication.instance().screenRemoved.disconnect(self._on_screens_changed)
        except (RuntimeError, TypeError):
            pass
        for win in self._windows:
            win.close()
        self._windows.clear()
        self.closed.emit()
